spring:
  application:
    name: orderquery
  kafka:
    bootstrap-servers: ${EVENTHUB_NAMESPACE}.servicebus.windows.net:9093
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${EVENTHUB_CONNECTION_STRING}";
  data:
    mongodb:
      database: orders
      host: ${MONGODB_HOST}