spring:
  application:
    name: orderquery
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    mongodb:
      database: orders
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}