spring:
  application:
    name: orderquery
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
  data:
    mongodb:
      database: orders
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}.global.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000